config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  
  resources :lists
  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :list
	validates_presence_of :list_id, :name, :description
	validates_uniqueness_of :name
	validates_inclusion_of :priority, in:[1,2,3,4,5], message: 'Needs to be 1 - 5'
	serialize :tags
end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :items, dependent: :destroy #best practice so it deletes id's associated with lists
	validates_presence_of :name, message: "Yo, man your name cannot be blank!" #first validation
	before_validation :set_name

	private
		def set_name
			self.name = 'Default Name' unless self.name
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new(list_id: params[:list_id])
  end

  def create
  	@item = Item.new(item_params)
      if @item.save
        redirect_to list_path(@item.list_id)
      else 
        render :new
      end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update
      redirect_to list_path(@items)
    else
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    if item.destroy
      redirect_to items_path
    else
      redirect_to items_path(item)
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :priority, :completed, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
  	# GET
  	# shows all the items
  	@lists = List.all
  end

  def show
  	# GET
  	# showing a single item or shows more information
  	@list = List.find(params[:id])
  	@items = @list.items
  end

  def new
  	# GET
  	# rendering the form to create a new item
  	@list = List.new
  	#@items = @list.item
  end

  def create
  	# POST
  	# Creates the list and redirects the user
  	@list = List.new(list_params)
  		if @list.save
  			redirect_to lists_path
  		else
  			render :new
  		end
  end

  def edit
  	# GET
  	# reder the form so we can edit a single item
  	@list = List.find(params[:id])
  end

  def update
  	# PUT
  	# updating the list and redirecting the user
  	@list = List.find(params[:id])
  	if @list.update(list_params)
  		redirect_to list_path(@list)
  	else
			render :edit  	
		end
  end

  def destroy
  	# DELETE
  	# finds the item, and removes it from the database
  	list = List.find(params[:id])
  	if list.destroy
  		redirect_to lists_path
  	else
  		redirect_to lists_path(list)
  	end
  end

  private

  def list_params
  	params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_form.html.erb
<% if @item.errors.any? %>
	<h4>Errors:</h4>
	<p><%= @item.errors.full_messages.join(', ') %></p>
	<hr />
<% end %>
<%= form_for @item do |f| %> 
<!-- this is like saying <form action "/items" method="POST"></form> -->
	<%= f.label :name %>
	<!-- <this is like saying label for="name">Name</label> -->
	<%= f.text_field :name %>
	<!-- <this is like saying input type="text" id="name" name="item[name]" /> -->
	<br />
	<%= f.label :description %>
	<!-- <label for="description">Description</label>-->
	<%= f.text_area :description %>
	<!-- <textarea id="description" name="item[description]"></textarea>-->
	<br />
	<%= f.label :priority %>
	<%= f.select :priority, [1,2,3,4,5,6,7,8,9,10] %>
	<br />
	<%= f.label :completed %>
	<!-- <label for="completed">Completed</label>-->
	<%= f.check_box :completed %>
	<!-- <input type="checkbox" id="completed" name="item[completed]" /> -->
	<br />
	<%= f.hidden_field :list_id %>
	<%= f.submit %>
	<!-- <input type="submit"> -->
	<br />
	<br />
	<%= link_to 'Back to Lists', lists_path %>
<% end %>

app/views/items/edit.html.erb
<!-- <p>Find me in app/views/items/edit.html.erb</p> -->
<h1> Editing Item With Name: <%= @item.name %></h1>
<br />
<%= render(partial: 'form') %>

app/views/items/new.html.erb
<h1>Add Items To List</h1>
<br />
<%= render(partial: 'form') %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<br />
<%= form_for @item do |f| %> 
<!-- this is like saying <form action "/items" method="POST"></form> -->
	<%= f.label :name %>
	<!-- <this is like saying label for="name">Name</label> -->
	<%= f.text_field :name %>
	<!-- <this is like saying input type="text" id="name" name="item[name]" /> -->
	<br />
	<%= f.label :description %>
	<!-- <label for="description">Description</label>-->
	<%= f.text_area :description %>
	<!-- <textarea id="description" name="item[description]"></textarea>-->
	<br />
	<%= f.label :priority %>
	<%= f.select :priority, [1,2,3,4,5,6,7,8,9,10] %>
	<br />
	<%= f.label :completed %>
	<!-- <label for="completed">Completed</label>-->
	<%= f.check_box :completed %>
	<!-- <input type="checkbox" id="completed" name="item[completed]" /> -->
	<br />
	<%= f.submit 'Add Item To List', edit_item_path(@item), method: :get %>
	<!-- <input type="submit"> -->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheRealTodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<div class="card">
  <div class="row">
    <div class="col s12 m8 offset-m2">
			<!-- This is an if/else statement that if no name was put it will return to create a new list-->
			<% if @list.errors.any? %>
				<h4>Errors:</h4>
				<p><%= @list.errors.messages.values.join(', ') %></p>
				<hr />
			<% end %>
			<!-- This is now a Partial form that is linked to other files -->
			<!-- Rails Helpers -->
			<div class="card-panel">
				<%= form_for @list do |f| %>
					<%= f.label :name %>
					<%= f.text_field :name %>
					<br />
					<%= f.submit 'Create New List' %>
					<hr />
					<%= link_to 'Back to Lists', lists_path %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/lists/edit.html.erb
<h1>Editing List With Name: <%= @list.name %></h1>
<br />
<%= render(partial: 'form') %>

app/views/lists/index.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m8 offset-m2">
			<br />
			<br />
			<%= image_tag("todolist.png", alt: "todolist") %>
			<hr>
			<% if @lists.any? %>
			<ul class="collection">
				<% @lists.each do |list| %>
				<li class="collection-item avatar">
					<i class="material-icons circle green">insert_chart</i>
					<h3 class="title"><%= link_to "#{list.name}", list_path(list) %></h3>
						<%= button_to 'Edit List', edit_list_path(list), class: "btn waves-effect waves-light", method: :get %>
						<br />
						<%= button_to "Delete", list_path(list), class: "btn waves-effect waves-light", method: :delete, data: {confirm: 'Do you really want to delete this list?'} %>
				</li>
				<% end %>
			</ul>
			<% else %>
				<h3>No lists to show</h3>
			<% end %>
			<hr />
			<%= link_to 'New List', new_list_path, class: "btn waves-effect waves-light" %>
		</div>
	</div>
</div>

app/views/lists/new.html.erb
<h1>Create A New List</h1>
<br>
<%= render(partial: 'form') %>

app/views/lists/show.html.erb
<h1>
	<%= @list.name %>
</h1>
<hr />
<!-- This is where a list is selected and the items display after being added to list-->
<% if @items.any? %>
  <ol>
	  <% @items.each do |item| %>
		  <li><%= item.name %></li>
	  <% end %>
  </ol>
<% else %>
	<h3>No items in the list, please create one</h3>
<% end %>
<%= link_to 'Create Item', new_item_path(list_id: @list.id) %>
<br />
<%= link_to 'Back to Lists', lists_path %>